version: "3"
services:
  postgres:
    image: "postgres:15"
    restart: always
    ports:
      - "5434:5434"
    environment:
      POSTGRESS_PASSWORD: 1946
      POSTGRESS_DB: banco
    container_name: dbbanco
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:90"
    depends_on:
      - postgres
